package plausibcheck.AddressTest

import com.neo.drools.model.Address;
import com.neo.drools.model.fact.AddressCheckResult;

rule "[Address-Test]"
agenda-group "address-test"
no-loop true
lock-on-active true
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("[Address-Test]规则中打印日志：校验通过!");
end