package plausibcheck.adress

import com.neo.drools.model.Address;
import com.neo.drools.model.fact.AddressCheckResult;

rule "[address] Postcode should be filled with exactly 5 numbers"
    agenda-group "address" // rule 分组
//    activation-group "address" //group里面只能执行一个rule
//    no-loop true // 避免循环调用
//    lock-on-active true  //ruleflow-group属性或agenda-group属性的时候， 避免循环调用
//    salience 3 //权重
//    dialect "java" //方言
//    date-effective "20-Jul-2018" //生效日期
//    date-expires "21-Jul-2019" //失效日期
//    enabled true //是否可用
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("[address]规则中打印日志：校验通过!");
end

rule "[copy-address] --> Postcode should be filled with exactly 5 numbers"
    agenda-group "address"
    activation-group "address"
    no-loop true
    lock-on-active true
    salience 1
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("[copy-address]规则中打印日志：校验通过!");
end